# Toggles between 'pcam' (binary image classification) and 'tcga' (multiclass embedding classification)
dataset_type: 'tcga' 

pcam_data:
  path: "./src/data/pcam"

tcga_data:
  pickle_path: "./src/data/tcga/traindata.pkl"
  val_split: 0.1 # 10% of data for validation

model:
  # --- For PCAM ---
  pcam_filters: 2

  # --- For TCGA / Quantum Heads ---
  # For QuantumHeadAmplitude, latent_dim will be automatically set to 2**n_qubits.
  # For QuantumHeadAngle, latent_dim will be equal to n_qubits.
  # For ClassicalHead, this is the embedding size before the final layer.
  latent_dim: 256
  n_qubits: 8 # For TCGA, latent_dim for Amplitude head will be 2**4 = 16
  n_quantum_layers: 1
  num_classes: 33 # Number of unique cancer types in TCGA dataset

  # 'amplitude' or 'angle'
  quantum_head_type: 'angle' 
  # 'strong' for StronglyEntanglingLayers or 'basic' for BasicEntanglerLayers
  entangling_layer: 'strong'

training:
  batch_size: 512
  lr: 1 
  epochs: 1
  num_workers: 0 #0 in case pcam